### ISSUE TITLE
No solver available

### ISSUE THREAD

**Issue by joeyxu95** [cdanielmachado/smetana#11]
Dear cdanielmachado,
I am using smetana with Python 3.7. There is one error when I run the progam as following. Would you please help me to figure out it. Thanks.
joeyxu@login1 13:12:14 /ufrc/nian/joeyxu/work/yunzeng/KOBASE/Fresh
$ smetana *.xml -d
Traceback (most recent call last):
  File "/apps/smetana/1.1.0/bin/smetana", line 89, in <module>
    main(
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/smetana/interface.py", line 341, in main
    entries, debug_entries = run_global(comm_id, community, organisms, medium_id, excluded_mets, env,
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/smetana/interface.py", line 132, in run_global
    mip, extras = mip_score(community, environment=env, verbose=verbose,
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/smetana/smetana.py", line 257, in mip_score
    noninteracting_medium, sol1 = minimal_medium(noninteracting.merged, exchange_reactions=exch_reactions,
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/reframed/cobra/medium.py", line 50, in minimal_medium
    solver = solver_instance(model)
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/reframed/solvers/__init__.py", line 73, in solver_instance
    solver = get_default_solver()
  File "/apps/smetana/1.1.0/lib/python3.8/site-packages/reframed/solvers/__init__.py", line 43, in get_default_solver
    raise RuntimeError("No solver available.")
RuntimeError: No solver available.

**Comment by joeyxu95** [comment]
I have addressed the problem. Thanks.

**Comment by susheelbhanu** [comment]
Hi @joeyxu95 I'm running into the same issue. Mind sharing how you solved this problem?

**Comment by zburcham** [comment]
Anyone solved this? I downloaded CPLEX and have it in in path but still get this error.
